### ISSUE TITLE
Page jitter/shake issue 

### ISSUE THREAD

**Issue by 4nur4g** [ChangoMan/nextjs-mdx-blog#6]
At first load, content appears on the screen after a jittery shake. The issue can be reproduced by reloading the page, also sometimes by going to a different route. 

I'm trying to fix it. However, I still need to find the cause of the issue.

**Comment by 4nur4g** [comment]
I just visited this link: https://nextjs-typescript-mdx-blog-pjvf23llx-changodaman.vercel.app/

On switching routes, the page shakes a bit.

**Comment by ChangoMan** [comment]
This should be fixed now with the recent update to the App router
